### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by justinpenner** [jenskutilek/Glyphs-Favourites#4]
A keyboard shortcut to toggle (open and close) the Favourites window would be handy. Glyphs doesn't use `Ctrl` for very many shortcuts, and it seems like some plugins have chosen to use it. I'm not sure if that's an established convention for Glyphs plugins, but it would be a good one. Perhaps `Ctrl-D` to resemble the Bookmarks/Favourites shortcut used by most browsers? `F` shortcuts are more often used for Find/Search functions.

**Comment by florianpircher** [comment]
The plugin could offer a menu item in the main menu somewhere. Then you could assign any shortcut you’d like in the Shortcut settings.

**Comment by jenskutilek** [comment]
Good idea. I've added `ctrl-D` to toggle the window.

@florianpircher It has an entry in the Window menu. I use [Paletro](https://appmakes.io/paletro) to quickly find and execute menu entries, that's why I didn't add a shortcut in the first place, it was quick enough for me :)
